import { Tiles } from "./Tiles.ts";

export class MapTiles extends Tiles
{
	public static TILE_WIDTH = 64;
	public static TILE_HEIGHT = 64;

	public static INDEX_GRASS = 0;
	public static INDEX_ROAD = 1;
	public static INDEX_TREE = 2;
	public static INDEX_TREE_END = 3;
	public static INDEX_BUSH = 4;

	constructor() {
		super();
		this.src = 'assets/tiles.png';
		this.layers = [
			[
				[MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_ROAD, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_GRASS, MapTiles.INDEX_TREE],
				[MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE, MapTiles.INDEX_TREE],
			],
			[
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_BUSH, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, Tiles.INDEX_EMPTY, MapTiles.INDEX_TREE_END],
				[MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END, MapTiles.INDEX_TREE_END],
			],
		]
	}
}